--- #THIS IS A LOOKUP FILE
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - debug: msg="lookup the SuperHero for BRUCE WAYNE  {{ lookup('csvfile','Wayne, file=lookup.csv delimiter=, default=NOMATCH') }}"
    - debug: msg="The ENV HOME variable is - {{ lookup('env','HOME') }}"
