--- # My First YAML Playbook for Ansible
- hosts: all
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
   playbook_version: 0.1b
  vars_files:
   - conf/copyright.yml
   - conf/webdefaults.yml
  tasks:
   - name: Install Apache Web Server
     action: yum name=httpd state=installed
     async: 300
     poll: 3
     notify: Restart HTTPD
  handlers:
  - name: Restart HTTPD
    action: service name=httpd state=restarted

#    - name: Install lynx web browser
#     action: yum name=lynx state=installed
#    - name: Check for telnet client
#     action: yum name=telnet state=absent
