--- #run once playbook example
 - hosts: all
   user: test
   sudo: yes
   connection: ssh
   gather_facts: no
   tasks: 
     - name: Run the uptime command on all systems
       raw: /usr/bin/uptime > /home/test/uptime.log
     - name: List the var directory 
       raw: ls -al /var >> /home/test/dir.list
       run_once: true

